sudo: required
language: node_js

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

env:
  matrix:
    - TABLEAU_SDK_VERSION=2018-3-0

node_js:
  - '6'
  - '8'
  - '10'

before_install:
  - wget --directory-prefix=$HOME/tableau-c-sdk https://downloads.tableau.com/tssoftware/extractapi-linux-x86_64-${TABLEAU_SDK_VERSION}.deb
  - sudo dpkg -i $HOME/tableau-c-sdk/extractapi-linux-x86_64-${TABLEAU_SDK_VERSION}.deb

install:
  - npm install

script:
  - export MALLOC_CHECK_=1
  - npm test
